### PR TITLE
Translate `themes/vue`

### PR DESCRIPTION
**Pull request by stakx**
@thilobillerbeck, @bwcgn - Should we review each others' translations via PRs, or should we just push to `master` directly? (I haven't tried yet whether I actually have push access.) IMHO, PRs are probably best for larger volumes of translation, so this one is actually a bad example since it's fairly minor. I thought I'd submit it anyway so that I can raise this question. :smile:

---

Files under `themes/vue` have already been translated for the largest part, here's a few that were still missing.

`themes/vue/partials/toc.ejs` is excluded from this PR, perhaps it makes more sense to incrementally update the English labels found therein as we advance with the translation.

### CODE REVIEW

**Comment by thilobillerbeck** [comment]
@stakx since I was doing this translation alone until now (and that's why the theme files are already translated), there was no need for a PR. You both have push access to this repository. I don't have problems with you pushing into the master branch, since we are only 3 people (minor volume, as you said) translating this documentation and I think we are able to do it well. In addition to that, we could keep a good pace by passing by the annoying process of reviewing our translations.

My thoughts were more on a second stage, where we review and correct the documentation to maintain a good pace in the first stage where we do the initial translation.

But since we are three maintainers at the moment, I really would like to hear @bwcgn 's opinion. :)

---

Thanks for translating the rest of the theme. :+1: For the advantage of keeping the progress of the translation visible to the maintainers, I agree with you that we should keep the progress based translation of `themes/vue/partials/toc.ejs`.

**Comment by bwcgn** [comment]
@stakx @thilobillerbeck I would like to have a PR for a larger translation. Small stuff can be pushed directly IMHO. 
But why are we talking english if we all translate this to german? ;)

**Comment by thilobillerbeck** [comment]
Because it is easier for the non german speaking Vue.js community to follow along the discussions as well as the project's progress.

**Comment by stakx** [comment]
@bwcgn - :+1: I think I'm siding with you on this: PRs for larger translations iff we take the time to review one another's work.

I've recently translated a somewhat larger page and it felt weird to just single-handedly decide on some special terms' translations without getting any feedback from you guys.

If you all prefer having discussions in German that's fine with me, but staying with English has the advantage that others can follow our progress. It might also help translators of other languages to see what kind of issues, discussion points, etc. might crop up, so they can go into their own translation a little more prepared. (For example, see how over at the French translation's issue tracker, they discussed whether to address their audience using "tu" or "vous". In principle, the same question applies to German as well, even if the answer might be different, for cultural or other reasons. But we might be able to profit from watching what they're thinking about, and that is easier if they're writing in a language we understand.)

I'd also like to see issues enabled on this repo in case we need to discuss anything in particular.

**Comment by thilobillerbeck** [comment]
I would like to know why I disabled them :laughing:

Ok, so we do PRs for large translations (pages etc.) and direct commits for smaller changes (single words etc.).

**Pull request merged**
